### PR TITLE
Multiplayer Functionality

### PR DESCRIPTION
**Pull request by misterperson**
Fix for #2 
Resolves errors in #3 :

- Double-click functionality works in Multiplayer. 
- Code added in Patches.cs moved to QuickStack.cs in "OnClick" delegates.
- Replaced boolean used in certain NetPackages with an enumeration.
- Reordered some checks and optimized some NetPackages to prevent useless sends.
- Fixed an issue where the PlatformId would differ from the Server's cached value, resulting in being unable to quick stack into owned, locked containers.

Testing for this commit was only conducted on a private dedicated server with no other players, but I believe the changes made do not introduce bugs for Singleplayer or Hosted sessions, which work as expected in #3.

Source/Patches.cs
Client: Clicks UI button to initiate a quickstack / restock

Source/NetPackages/NetPackageFindOpenableContainers.cs
Server: Receives request and populates a list of allowed containers, marking them all as in-use.

Source/NetPackages/NetPackageDoQuickStack.cs
Client: Quickstacks / restocks into all containers and notifies server they can be unlocked.

Source/NetPackages/NetPackageUnlockContainers.cs
Server: Marks all containers listed as not in-use

### CODE REVIEW

**Comment by misterperson** [comment]
I found a bug in playtesting: The host always stacks and never restocks.

**Comment by misterperson** [comment]
I pushed changes pretty much a day after commenting on a bug. I've since used this version on a hosted game for around 40 hours of gameplay with 5 people on it playing out of the same base without running into any issues.

**Comment by Westwud1** [comment]
Thank you. Great to hear that it's running smoothly for your players. Please let me know how you would like to be credited on the mod page.

**Comment by misterperson** [comment]
I'd like to be credited as "NoHomeLike192.168.8.1"

**Comment by Westwud1** [comment]
HI @misterperson , great work with the multiplayer functionality. Though there was a report that an error was thrown when trying to use quickstock/resock in a co-op game (I'm assuming hosting through steam instead of a dedicated server).

https://forums.nexusmods.com/index.php?/topic/9851708-quickstack/?p=112459893

>EXC MissingMethodException: PlatformUserldentifierAbs PersistentPlayerData.get_PlatformUserldentifier()

> It appears when trying to use the mod, if there is at least one connected player (played in a regular co-op game, without running a dedicated server). The button is pressed, this message appears in the console, and nothing else happens. The message to the console is the same regardless of which player, server or client, presses the button.

> If there are no connected players, then the mod works as expected. Items are replenished in chests.

I'm assuming this could be the cause, but I do not have anyone to test it with:

https://github.com/Westwud1/QuickStack/blob/be31a85a2e01eaed0840873d54de7af2b25bc1cc/Source/QuickStack.cs#L47-L53

Do you think removing the second part of the check could fix this?

If it's not too much of an issue, would you be able to test this/try reproduce the error message? Thanks.

**Comment by misterperson** [comment]
The most recent change to 7 Days to Die is doing authentication exclusively through Epic Online Services (for a newer version of EAC). PlatformUserIdentifier (i.e. tracking Steam IDs) must have been dropped in favor of EOS-generated identifiers.
I can test this tonight on a dedicated server, and if the dedicated server also uses EOS exclusively, it will be an easy removal. Otherwise, that check will also have to include​ checking if the dedicated server is the one doing it.
Worst case, Harmony might have to be used to check if the method exists before attempting to call it (something that would work on versions before & after the EAC changes).

My friends are currently invested in other games at the moment, and my go-to to test with currently has a fever.
If you would like, we can schedule a test with the host-client version, as well.

________________________________

**Pull request merged**
